apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"traefik","meta.helm.sh/release-namespace":"traefik","metallb.universe.tf/adress-pool":"first-pool","metallb.universe.tf/ip-allocated-from-pool":"first-pool"},"creationTimestamp":"2023-05-12T13:44:56Z","labels":{"app.kubernetes.io/instance":"traefik-traefik","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"traefik","helm.sh/chart":"traefik-23.0.1"},"name":"traefik","namespace":"traefik","resourceVersion":"2887717","uid":"3d496559-f2c0-423b-bab6-3335e69da4ec"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.97.223.138","clusterIPs":["10.97.223.138"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"traefik","nodePort":32181,"port":9000,"protocol":"TCP","targetPort":"traefik"},{"name":"web","nodePort":30118,"port":80,"protocol":"TCP","targetPort":"web"},{"name":"websecure","nodePort":32590,"port":443,"protocol":"TCP","targetPort":"websecure"}],"selector":{"app.kubernetes.io/instance":"traefik-traefik","app.kubernetes.io/name":"traefik"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"193.147.109.10"}]}}}
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
    metallb.universe.tf/adress-pool: first-pool
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  creationTimestamp: "2023-10-06T12:54:16Z"
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-23.0.1
  name: traefik
  namespace: traefik
  resourceVersion: "29831691"
  uid: 6c4ec590-2b55-487b-8ebe-0fe20c1738f5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.223.138
  clusterIPs:
  - 10.97.223.138
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: traefik
    nodePort: 32181
    port: 9000
    protocol: TCP
    targetPort: traefik
  - name: web
    nodePort: 30118
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 32590
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 193.147.109.10