apiVersion: v1
data:
  secretkey: Vzh2SGUybXFVR2ZDaUM5YXh0dUNoU1BZS21IMm5jT01GcHlIT0xFTXNnb3YwSC90NjFLS0pUN0orYnVTUndkKwowRllqNktuSmdzYU53V0hFQlFNREpkS29JOEM1YWZNVnZPaXZZSkFFNDFvOFhZY2g1bnlqZGl4ckZhd0I4QnkzCjQ3ZGxrdjNhQVM1VXVwbFR4eVFDSGNQd3NIQXNsNXRrdGNvTUd2emJxa2s9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
